"""initial schema: tenant, user, account, payment_network, exception_item, decision, ml_model

Revision ID: 18baeeaca329
Revises: 
Create Date: 2026-07-18 16:43:46.024722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18baeeaca329'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_network',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('settlement_timing', sa.Enum('ASYNC_REVIEWABLE', 'SYNCHRONOUS_AUTHORIZATION', name='settlement_timing', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_payment_network'))
    )
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('require_dual_control', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ach_debit_block_mode', sa.Enum('BLOCK_ALL', 'FILTER_BY_AUTHORIZATION', name='ach_debit_block_mode', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_account_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('tenant_id', 'account_number', name='uq_account_tenant_number')
    )
    op.create_index(op.f('ix_account_tenant_id'), 'account', ['tenant_id'], unique=False)
    op.create_table('exception_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('network_code', sa.String(length=32), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('related_reference_id', sa.Uuid(), nullable=True),
    sa.Column('exception_types', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING_APPROVAL', 'PAY', 'RETURN', 'ESCALATED', name='exception_status', native_enum=False, length=20), nullable=False),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('ml_model_version', sa.String(length=64), nullable=True),
    sa.Column('decision_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['network_code'], ['payment_network.code'], name=op.f('fk_exception_item_network_code_payment_network')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_exception_item_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_item'))
    )
    op.create_index(op.f('ix_exception_item_network_code'), 'exception_item', ['network_code'], unique=False)
    op.create_index(op.f('ix_exception_item_source_item_id'), 'exception_item', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_exception_item_tenant_id'), 'exception_item', ['tenant_id'], unique=False)
    op.create_table('ml_model',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_code', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('trained_from_decision_count', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('TRAINING', 'ACTIVE', 'RETIRED', 'FAILED', name='ml_model_status', native_enum=False, length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['network_code'], ['payment_network.code'], name=op.f('fk_ml_model_network_code_payment_network')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_model'))
    )
    op.create_index(op.f('ix_ml_model_network_code'), 'ml_model', ['network_code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PREPARER', 'APPROVER', 'VIEWER', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_user_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('exception_item_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('PAY', 'RETURN', name='decision_outcome', native_enum=False, length=10), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], name=op.f('fk_decision_decided_by_user_id_user')),
    sa.ForeignKeyConstraint(['exception_item_id'], ['exception_item.id'], name=op.f('fk_decision_exception_item_id_exception_item')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], name=op.f('fk_decision_submitted_by_user_id_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_decision_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    op.create_index(op.f('ix_decision_exception_item_id'), 'decision', ['exception_item_id'], unique=True)
    op.create_index(op.f('ix_decision_tenant_id'), 'decision', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_tenant_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_exception_item_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ml_model_network_code'), table_name='ml_model')
    op.drop_table('ml_model')
    op.drop_index(op.f('ix_exception_item_tenant_id'), table_name='exception_item')
    op.drop_index(op.f('ix_exception_item_source_item_id'), table_name='exception_item')
    op.drop_index(op.f('ix_exception_item_network_code'), table_name='exception_item')
    op.drop_table('exception_item')
    op.drop_index(op.f('ix_account_tenant_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_table('payment_network')
    # ### end Alembic commands ###
