# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chaffed

"""ach network: ach_authorization_rule, ach_transaction

Revision ID: 20876d626ec0
Revises: 523fe5e5312e
Create Date: 2026-07-18 17:29:51.069034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20876d626ec0'
down_revision: Union[str, None] = '523fe5e5312e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ach_authorization_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('originator_id', sa.String(length=32), nullable=False),
    sa.Column('originator_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='ach_authorization_status', native_enum=False, length=20), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frequency_limit', sa.Integer(), nullable=True),
    sa.Column('allowed_sec_codes', sa.JSON(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_ach_authorization_rule_account_id_account')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_ach_authorization_rule_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ach_authorization_rule_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ach_authorization_rule'))
    )
    op.create_index(op.f('ix_ach_authorization_rule_account_id'), 'ach_authorization_rule', ['account_id'], unique=False)
    op.create_index(op.f('ix_ach_authorization_rule_tenant_id'), 'ach_authorization_rule', ['tenant_id'], unique=False)
    op.create_table('ach_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('originator_id', sa.String(length=32), nullable=False),
    sa.Column('originator_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEBIT', 'CREDIT', name='ach_transaction_type', native_enum=False, length=10), nullable=False),
    sa.Column('sec_code', sa.String(length=3), nullable=False),
    sa.Column('trace_number', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('match_status', sa.Enum('PENDING', 'MATCHED', 'EXCEPTION', name='ach_match_status', native_enum=False, length=20), nullable=False),
    sa.Column('settlement_status', sa.Enum('PENDING', 'PAID', 'RETURNED', name='ach_settlement_status', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('API', 'BULK_FILE', 'MANUAL', name='ach_transaction_source', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_ach_transaction_account_id_account')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ach_transaction_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ach_transaction')),
    sa.UniqueConstraint('tenant_id', 'trace_number', name='uq_ach_transaction_tenant_trace')
    )
    op.create_index(op.f('ix_ach_transaction_account_id'), 'ach_transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_ach_transaction_tenant_id'), 'ach_transaction', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ach_transaction_tenant_id'), table_name='ach_transaction')
    op.drop_index(op.f('ix_ach_transaction_account_id'), table_name='ach_transaction')
    op.drop_table('ach_transaction')
    op.drop_index(op.f('ix_ach_authorization_rule_tenant_id'), table_name='ach_authorization_rule')
    op.drop_index(op.f('ix_ach_authorization_rule_account_id'), table_name='ach_authorization_rule')
    op.drop_table('ach_authorization_rule')
    # ### end Alembic commands ###
