# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chaffed

"""add receiver_id filtering to ach authorizations and transactions

Revision ID: 46b83c93faca
Revises: 6b9b23b81e31
Create Date: 2026-07-22 07:43:30.920811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46b83c93faca'
down_revision: Union[str, None] = '6b9b23b81e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ach_authorization_rule', sa.Column('receiver_id', sa.String(length=32), nullable=True))
    op.add_column('ach_transaction', sa.Column('receiver_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ach_transaction', 'receiver_id')
    op.drop_column('ach_authorization_rule', 'receiver_id')
    # ### end Alembic commands ###
