"""add webauthn credential and challenge tables for FIDO2 second-factor auth

Revision ID: 51624395f2fb
Revises: 46b83c93faca
Create Date: 2026-07-22 08:01:05.096502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51624395f2fb'
down_revision: Union[str, None] = '46b83c93faca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'AUTHENTICATION', name='webauthn_challenge_purpose', native_enum=False, length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_webauthn_challenge_tenant_id_tenant')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_webauthn_challenge_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_challenge'))
    )
    op.create_index(op.f('ix_webauthn_challenge_tenant_id'), 'webauthn_challenge', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webauthn_challenge_user_id'), 'webauthn_challenge', ['user_id'], unique=False)
    op.create_table('webauthn_credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_webauthn_credential_tenant_id_tenant')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_webauthn_credential_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_credential')),
    sa.UniqueConstraint('credential_id', name='uq_webauthn_credential_credential_id')
    )
    op.create_index(op.f('ix_webauthn_credential_tenant_id'), 'webauthn_credential', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webauthn_credential_user_id'), 'webauthn_credential', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credential_user_id'), table_name='webauthn_credential')
    op.drop_index(op.f('ix_webauthn_credential_tenant_id'), table_name='webauthn_credential')
    op.drop_table('webauthn_credential')
    op.drop_index(op.f('ix_webauthn_challenge_user_id'), table_name='webauthn_challenge')
    op.drop_index(op.f('ix_webauthn_challenge_tenant_id'), table_name='webauthn_challenge')
    op.drop_table('webauthn_challenge')
    # ### end Alembic commands ###
