# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chaffed

"""add check_image table

Revision ID: 523fe5e5312e
Revises: cd4dc7cc709b
Create Date: 2026-07-18 17:13:03.638332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '523fe5e5312e'
down_revision: Union[str, None] = 'cd4dc7cc709b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('paid_item_id', sa.Uuid(), nullable=True),
    sa.Column('front_image_path', sa.String(length=1000), nullable=False),
    sa.Column('back_image_path', sa.String(length=1000), nullable=True),
    sa.Column('ocr_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='ocr_status', native_enum=False, length=20), nullable=False),
    sa.Column('ocr_raw_result', sa.JSON(), nullable=True),
    sa.Column('ocr_extracted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ocr_extracted_payee', sa.String(length=255), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_provider', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paid_item_id'], ['paid_item.id'], name=op.f('fk_check_image_paid_item_id_paid_item')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_check_image_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_image'))
    )
    op.create_index(op.f('ix_check_image_paid_item_id'), 'check_image', ['paid_item_id'], unique=False)
    op.create_index(op.f('ix_check_image_tenant_id'), 'check_image', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_image_tenant_id'), table_name='check_image')
    op.drop_index(op.f('ix_check_image_paid_item_id'), table_name='check_image')
    op.drop_table('check_image')
    # ### end Alembic commands ###
