# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chaffed

"""check network: issued_item, stop_payment, paid_item; exception_item recommendation fields; tenant stale_date_threshold_days

Revision ID: cd4dc7cc709b
Revises: 9327972d0952
Create Date: 2026-07-18 17:02:00.625636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd4dc7cc709b'
down_revision: Union[str, None] = '9327972d0952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('check_number', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payee_name', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OUTSTANDING', 'PAID', 'VOIDED', 'STOPPED', 'STALE', name='issued_item_status', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('API', 'BULK_FILE', 'MANUAL', name='issued_item_source', native_enum=False, length=20), nullable=False),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_issued_item_account_id_account')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], name=op.f('fk_issued_item_submitted_by_user_id_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_issued_item_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issued_item')),
    sa.UniqueConstraint('tenant_id', 'account_id', 'check_number', name='uq_issued_item_tenant_account_check')
    )
    op.create_index(op.f('ix_issued_item_account_id'), 'issued_item', ['account_id'], unique=False)
    op.create_index(op.f('ix_issued_item_tenant_id'), 'issued_item', ['tenant_id'], unique=False)
    op.create_table('stop_payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('check_number', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='stop_payment_status', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_stop_payment_account_id_account')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_stop_payment_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_stop_payment_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_payment'))
    )
    op.create_index(op.f('ix_stop_payment_account_id'), 'stop_payment', ['account_id'], unique=False)
    op.create_index(op.f('ix_stop_payment_tenant_id'), 'stop_payment', ['tenant_id'], unique=False)
    op.create_table('paid_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('check_number', sa.String(length=32), nullable=False),
    sa.Column('presented_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('presented_date', sa.Date(), nullable=False),
    sa.Column('matched_issued_item_id', sa.Uuid(), nullable=True),
    sa.Column('match_status', sa.Enum('PENDING', 'MATCHED', 'EXCEPTION', name='paid_item_match_status', native_enum=False, length=20), nullable=False),
    sa.Column('settlement_status', sa.Enum('PENDING', 'PAID', 'RETURNED', name='paid_item_settlement_status', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('API', 'BULK_FILE', 'MANUAL', name='paid_item_source', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_paid_item_account_id_account')),
    sa.ForeignKeyConstraint(['matched_issued_item_id'], ['issued_item.id'], name=op.f('fk_paid_item_matched_issued_item_id_issued_item')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_paid_item_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paid_item'))
    )
    op.create_index(op.f('ix_paid_item_account_id'), 'paid_item', ['account_id'], unique=False)
    op.create_index(op.f('ix_paid_item_tenant_id'), 'paid_item', ['tenant_id'], unique=False)
    op.add_column('exception_item', sa.Column('recommended_outcome', sa.String(length=10), nullable=True))
    op.add_column('exception_item', sa.Column('recommended_reason_code', sa.String(length=64), nullable=True))
    op.add_column('exception_item', sa.Column('recommended_notes', sa.String(length=1000), nullable=True))
    op.add_column('exception_item', sa.Column('recommended_by_user_id', sa.Uuid(), nullable=True))
    with op.batch_alter_table('exception_item') as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_exception_item_recommended_by_user_id_user'), 'user', ['recommended_by_user_id'], ['id']
        )
    op.add_column(
        'tenant',
        sa.Column('stale_date_threshold_days', sa.Integer(), nullable=False, server_default='180'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'stale_date_threshold_days')
    with op.batch_alter_table('exception_item') as batch_op:
        batch_op.drop_constraint(op.f('fk_exception_item_recommended_by_user_id_user'), type_='foreignkey')
    op.drop_column('exception_item', 'recommended_by_user_id')
    op.drop_column('exception_item', 'recommended_notes')
    op.drop_column('exception_item', 'recommended_reason_code')
    op.drop_column('exception_item', 'recommended_outcome')
    op.drop_index(op.f('ix_paid_item_tenant_id'), table_name='paid_item')
    op.drop_index(op.f('ix_paid_item_account_id'), table_name='paid_item')
    op.drop_table('paid_item')
    op.drop_index(op.f('ix_stop_payment_tenant_id'), table_name='stop_payment')
    op.drop_index(op.f('ix_stop_payment_account_id'), table_name='stop_payment')
    op.drop_table('stop_payment')
    op.drop_index(op.f('ix_issued_item_tenant_id'), table_name='issued_item')
    op.drop_index(op.f('ix_issued_item_account_id'), table_name='issued_item')
    op.drop_table('issued_item')
    # ### end Alembic commands ###
